[package]
name = "breez-capture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
breez-core.workspace = true
breez-codec.workspace = true
pinray.workspace = true
rdev.workspace = true
crossbeam-channel.workspace = true
thiserror.workspace = true
log.workspace = true

[dev-dependencies]
env_logger.workspace = true
